name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release package
        run: >-
          git clone --depth 1
          "https://github.com/${GITHUB_REPOSITORY}.git" .

      - name: Upload prepared site
        uses: ./.github/vendor/upload-artifact
        with:
          name: github-pages
          path: .github/deploy/artifact.tar
          if-no-files-found: error
          retention-days: 1
          compression-level: 6
          overwrite: false
          include-hidden-files: true

      - name: Deploy Pages
        id: deployment
        uses: ./.github/vendor/deploy-pages
